layout_spectrum: 0.3101975
typography_spectrum: 1
color:
  saturation: 0.5928063
  brandStrength: 0.7690374
  lightness: 0.6539877
  rhythmicContrast: 0.5128894
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: jayyao
